/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    FAQItem: typeof import('./src/components/FAQItem.vue')['default']
    IconChevronDown: typeof import('./src/components/icons/IconChevronDown.vue')['default']
    IconChocolateMenu: typeof import('./src/components/icons/IconChocolateMenu.vue')['default']
    IconDiscord: typeof import('./src/components/icons/IconDiscord.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconInstagram: typeof import('./src/components/icons/IconInstagram.vue')['default']
    IconLinkedin: typeof import('./src/components/icons/IconLinkedin.vue')['default']
    IconMessage: typeof import('./src/components/icons/IconMessage.vue')['default']
    IconTwitter: typeof import('./src/components/icons/IconTwitter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
